id: P1F1F7DFC
initial_creation_type: input
source_metadata:
  title: Amitāyus Series
  language: fr
  description: 'Texts related to Amitāyus (tshe dpag med), the Buddha of Boundless
    Life:'
  volume:
    053cd860e3c5473c80a3d1670539df84:
      title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
        White and Red Amitāyus'
      parent: Lineage Prayers
    16d905d2435a421cb297bb57dfa9b181:
      title: A Prayer to Amitāyus
      parent: Prayers
    51da29fa7783468e987714500e8b6c88:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    19b9599ec7ff424f9770bdf67c52aef9:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
    f36aebe5d7054c85b0c37cddce03d378:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Sādhanas
    79c8af5bee2b4bb6af6e9a0ad6cca49e:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Sādhanas
    1fc35afed60d43fb9e223a551db45846:
      title: The Dhāraṇī of Amitāyus
      parent: Sūtra
    fbe9a2207576467090e5c97e72126bd5:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtra
    84384d2592af40a99dc63c87a67f9dae:
      title: How to Recite the Dhāraṇīsūtra of Amitāyus
      parent: Sūtra
created_at: '2022-03-01T02:43:20.957329'
last_modified_at: '2022-03-01T02:43:20.957332'
